# Uncomment this line to define a global platform for your project
 platform :ios, "7.0"

target "RACPlayground" do
  pod 'ReactiveCocoa', '2.1.4'
end

target "RACPlaygroundTests" do
  pod 'ReactiveCocoa', '2.1.4'
end

