# Uncomment this line to define a global platform for your project
 platform :ios, "7.0"

target "FunctionalReactivePixels" do
  pod 'ReactiveCocoa', '2.1.4'
end

target "FunctionalReactivePixelsTests" do
  pod 'ReactiveCocoa', '2.1.4'
end

