# Uncomment this line to define a global platform for your project
 platform :ios, "7.0"

target "FunctionalReactivePixels" do
  pod 'ReactiveCocoa', '2.1'
  pod 'libextobjc', '0.3'
  pod '500px-iOS-api', '1.0.4'
  pod 'SVProgressHUD', '0.9'
end

target "FunctionalReactivePixelsTests" do
end

